spring.application.name=JournalApp
app.mongodb.default-uri=mongodb+srv://greatmanfor01_db_user:yB07Nya80ui8Fu9i@cluster0.l4wiwxi.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
spring.mongodb.uri=${MONGODB_URI:${app.mongodb.default-uri}}
spring.mongodb.database=${MONGODB_DATABASE:journaldb}
spring.data.mongodb.auto-index-creation=${MONGODB_AUTO_INDEX_CREATION:false}
logging.level.net.engineeringDigestt.JournalApp=DEBUG
#logging.level.root=ERROR
#logging.level.root=OFF
weather.api.key=1a176bbf507463552d6b02b3de004d70

# 1. SMTP Server Host and Port (e.g., Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# 2. Your Email Account Credentials
spring.mail.username=greatmanfor01@gmail.com
# CRITICAL: For Gmail/Outlook, use an 'App Password', NOT your account password
spring.mail.password=ktqdvftusxhqtscl

# 3. Protocol and Security Settings
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# 4. Optional: Connection Timeouts (Good practice to avoid hanging threads)
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=3000

spring.redis.host=redis://default:nqUWUQNXrv5hP3G3WBlh28Ll5TGwqit1@collar-cracker-statement-97324.db.redis.io:19906
spring.redis.port=6379